
import React, { useMemo } from 'react';
import { XIcon } from './icons/Icons';
import { getPromptDJHTMLContent } from './promptdj-html-content';
import { GEMINI_API_KEY } from '../config';

interface PromptDJModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const PromptDJModal: React.FC<PromptDJModalProps> = ({ isOpen, onClose }) => {
    // The iframe's content is generated by calling getPromptDJHTMLContent with the
    // necessary API key. This makes the component self-contained.
    const iframeSrcDoc = useMemo(() => {
        if (!GEMINI_API_KEY || GEMINI_API_KEY.includes('PASTE_YOUR')) {
            // Display an error message inside the iframe if the API key is not configured.
            return `
                <body style="background-color: #111; color: #fff; font-family: sans-serif; text-align: center; padding: 2rem;">
                    <h1>Configuration Error</h1>
                    <p>The Gemini API Key is missing. Please configure it in <strong>config.ts</strong> to use PromptDJ.</p>
                </body>
            `;
        }
        return getPromptDJHTMLContent(GEMINI_API_KEY);
    }, []); // API key is a constant, so this runs only once.

    if (!isOpen) return null;

    return (
        <div 
            className="fixed inset-0 bg-primary/90 z-50 flex items-center justify-center p-4 backdrop-blur-sm"
            aria-modal="true"
            role="dialog"
        >
            <div 
                className="bg-secondary rounded-xl shadow-2xl w-full h-full max-w-7xl max-h-[90vh] border border-gray-700/50 relative flex flex-col"
                onClick={e => e.stopPropagation()}
            >
                <div className="flex items-center justify-between p-4 border-b border-gray-700/50 shrink-0">
                    <h2 className="text-lg font-semibold text-text-primary">PromptDJ</h2>
                    <button onClick={onClose} className="p-1 rounded-full text-text-secondary hover:bg-gray-700">
                        <XIcon className="w-6 h-6" />
                    </button>
                </div>
                <div className="flex-grow w-full h-full p-0 m-0 overflow-hidden flex items-center justify-center bg-black">
                    <iframe 
                        srcDoc={iframeSrcDoc}
                        title="PromptDJ"
                        className="w-full h-full border-0"
                        // 'allow-scripts' is required for the JavaScript in the iframe to run.
                        // 'allow-same-origin' is critical for srcDoc content and its scripts.
                        sandbox="allow-scripts allow-same-origin"
                    />
                </div>
            </div>
        </div>
    );
};
